// Generated by https://quicktype.io
import { ApiResponseSuccess } from './api';

export interface GetCourseRequest {
	rows?: number;
}

export type GetCourseResponse = ApiResponseSuccess<Course[]>;

export interface GetCouseByIdRequest {
	id: number | undefined;
}
export type GetCourseByIdResponse = ApiResponseSuccess<Course>;

export type Course = Partial<{
	id: number;
	path_thumbnail: string;
	judul_pelatihan: string;
	penyelenggara: string;
	angkatan: string;
	informasi_umum: string;
	waktu_mulai: string;
}>;
